decode:
  v0_10_1:
    train:
      app:
        cmd:
          - |
            --calib_path="$(find /files/config -name '*.mat' | head -n 1)"
          - |
            --param_path="$(find /files/config -name '*.yaml' | head -n 1)"
          - "--model_path=/files/model"
          - "--log_path=/files/log"
        env: []
      handler:
        image_url: "eu-central-1.console.aws.amazon.com/ecr/repositories/private/367538675956/decode_repository_dev?region=eu-central-1"
        files_down:
          config_id: config
          data_ids: data
          artifact_ids: artifact
        files_up:
          log: log
          artifact: model
      aws_resources:
        hardware:
          MEMORY: 8000
          VCPU: 4
          GPU: 1
        timeout: 18000