decode:
  dev_multiphot_tar:
    train:
      app:
        cmd: ["--config-dir=/files/config", "--config-name=config", "Paths.experiment=/files/model", "Paths.logging=/files/log"]
        env: ["wandb_api_key"]
      handler:
        image_url: "public.ecr.aws/d2r7a3u1/decode:dev_multiphot_tar"
        files_down:
          config_id: config
          data_ids: data
          artifact_ids: artifact
        files_up:
          log: log
          artifact: model
      aws_resources:
        hardware:
          MEMORY: 8000
          VCPU: 4
          GPU: 1
        timeout: 18000