decode:
  v0_10_1:
    train:
      app:
        cmd:
          - "/docker/entrypoint.sh"
          - "--train"
          - "--calib_path=$(find /files/data -name '*.mat' | head -n 1)"
          - "--param_path=$(find /files/config -name '*.yaml' | head -n 1)"
          - "--model_path=/files/model"
          - "--log_path=/files/log"
        env: []
      handler:
        image_url: "public.ecr.aws/g0e9g3b1/decode:v0_10_1"
        files_down:
          config_id: config
          data_ids: data
          artifact_ids: artifact
        files_up:
          log: log
          artifact: model
      aws_resources:
        hardware:
          MEMORY: 8000
          VCPU: 4
          GPU: 1
        timeout: 18000
    fit:
      app:
        cmd:
          - "/docker/entrypoint.sh"
          - "--fit"
          - "--frame_path=$(find /files/data -name '*.tif*' | head -n 1)"  # matches both .tif and .tiff
          - "--frame_meta_path=$(find /files/config -name '*.yaml' | head -n 1)"
          - "--model_path=$(find /files/artifact/model -type d -maxdepth 1 | head -n 1)"
          - "--emitter_path=/files/output/emitter.h5"
        env: []
      handler:
        image_url: "public.ecr.aws/g0e9g3b1/decode:v0_10_1"
        files_down:
          config_id: config
          data_ids: data
          artifact_ids: artifact
        files_up:
          artifact: output
      aws_resources:
        hardware:
          MEMORY: 8000
          VCPU: 4
          GPU: 1
        timeout: 18000
  latest:
    train:
      app:
        cmd:
          - "mkdir /files/config &&"
          - "python -m cli.config /files/config &&"
          - "cp -r /files/config_tmp/* /files/config &&"
          - "python -m cli.train"
          - "--config-path=/files/config"
          - "--config-name=/files/config/conf_run"
          - "Paths.calibration=$(find /files/data -name '*_3dcal.mat' | head -n 1)"
          - "Paths.experiment=/files/model"
          - "Paths.logging=/files/log"
          - "Paths.trafo=$(find /files/data -name '*_trafo.mat' | head -n 1 | grep . || echo null)"
        env: []
      handler:
        image_url: "public.ecr.aws/g0e9g3b1/decode:latest"
        files_down:
          config_id: config_tmp
          data_ids: data
          artifact_ids: artifact
        files_up:
          log: log
          artifact: model
      aws_resources:
        hardware:
          MEMORY: 8000
          VCPU: 4
          GPU: 1
        timeout: 18000

comet:
  latest:
    run:
      app:
        cmd:
          - "mkdir -p /files/log &&"
          - "python -m docker_entrypoint"
          - "--localizations_path=$(ls /files/data/*.csv /files/data/*.h5 2>/dev/null | head -n 1)"
          - "--param_path=$(find /files/config -name '*.yaml' | head -n 1)"
          - "--output_path=/files/output"
          - " > /files/log/log.log"
        env: []
      handler:
        image_url: "public.ecr.aws/g0e9g3b1/comet:latest"
        files_down:
          config_id: config
          data_ids: data
          artifact_ids: artifact
        files_up:
          log: log
          output: output
      aws_resources:
        hardware:
          MEMORY: 15000
          VCPU: 4
          GPU: 1
        timeout: 18000
